networks:
  app_net:
    driver: bridge
services: 
  nodejs:
    build: ./be
    hostname: node
    networks:
      - app_net

  web_nginx:
    build: ./web
    hostname: web_nginx
    networks:
      - app_net
    ports:
      - 80:80
      # no certs so https doesn't work
      # - 443:443
    # volumes:
      # populate certificates to nginx container
      # but actually this is an anti-pattern, only done it to check if it will work once      
      # - /home/michal/letsencrypt-copy/archive/:/etc/nginx/certs/
    
    