networks:
  app_net:
    driver: bridge
services:
  web_nginx:
    build: ./web
    hostname: web_nginx
    networks:
      - app_net
    ports:
      - 443:443
    volumes:
      - /home/michal/letsencrypt-copy/archive/:/etc/nginx/certs/
  nodejs:
    build: ./be
    hostname: node
    networks:
      - app_net
    depends_on:
      - web_nginx
    